/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    backgroundColor: '#F6F5F5',
    width: '100%',
    height: '100%',
  },
  titleContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignSelf: 'center',
  },
  headerTitle: {
    color: 'rgba(78, 78, 75, 0.84)',
    zIndex: 1,
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontSize: 80,
    fontWeight: '400',
    lineHeight: 116,
    letterSpacing: 2.59,
  },
  headerTitleSmall: {
    color: '#fff',
    fontFamily: 'Inter',
    fontStyle: 'normal',
    fontSize: 80,
    fontWeight: '400',
    lineHeight: 116,
    textAlign: 'center',
    letterSpacing: 2.59,
  },
  semiheaderTitleContainer: {
    position: 'absolute',
  },
  semiheaderTitle: {
    position: 'absolute',

    marginVertical: 106,
    marginHorizontal: 100,

    fontFamily: 'Inter',
    fontSize: 18,
    fontWeight: '100',

    letterSpacing: 1.59,

    color: ' rgba(0, 0, 0, 0.57)',
  },
  semiheaderTitleBelow: {
    position: 'absolute',
    width: 200,
    marginHorizontal: 70,
    top: 122,
    fontFamily: 'Inter',
    fontSize: 28,
    fontWeight: '600',
    letterSpacing: 4.59,
    color: ' rgba(0, 0, 0, 0.57)',
  },
  image: {
    aspectRatio: 1 / 1,
    flex: 1,
    justifyContent: 'center',
    zIndex: -1,
    position: 'absolute',
    top: 0,
    left: '12%',
    bottom: 0,
    right: 0,
  },
  imgMen: {
    alignSelf: 'flex-end',
    marginRight: '3%',
    top: '-9%',
    // width: '52%',
    // height: '10%',
  },
  pressableContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    // paddingVertical: 20,
    backgroundColor: '#F6F5F5',
    width: '100%',
    height: '100%',
    borderColor: 'rgba(0, 0, 0, 0.54);',
    borderTopWidth: 1.5,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderLeftColor: '#000',
    borderRightColor: '#000',
    borderRadius: 44,
    zIndex: 1,
    bottom: '25%',
    // paddingBottom: '100%',
    // top: '-25%',
    // marginVertical: '-48%',
  },
  scroll: {
    flex: 1,
    borderColor: 'rgba(0, 0, 0, 0.54);',
    borderTopWidth: 1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    marginTop: '-13%',
    backgroundColor: '#F6F5F5',
    // marginBottom: '10%',
  },
  Boxshadow: {
    shadowColor: 'rgba(0, 0, 0, 0.1)',

    shadowOffset: {width: 0, height: 1},

    shadowRadius: 3,

    elevation: 1.5,
  },
  loading: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 390,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5FCFF88',
    zIndex: 1000,
  },
  spinnerTextStyle: {
    color: '#FFF',
  },
  arrow: {
    zIndex: 1000,
  },
});
